import { Nunito } from "next/font/google";
import './globals.css'

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-[#F1F1F1]`}>{children}</body>
    </html>
  );
}
